### ISSUE TITLE
Test cases not working - Typescript

### ISSUE THREAD

**Issue by dkaus1** [s-yadav/react-number-format#180]
I am using this component with typescript.  Code works as expected using import * as NumberFormat from  'react-number-format' but  Jest unit test fails. In order to run UTC's import NumberFormat from 'react-number-format'  works.

Can you please suggest a workaround so that it works both ways UI as well UTC ??

**Comment by satyamamit** [comment]
I am also facing exact same issue. My tests are failing with error :  Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

**Comment by horacehylee** [comment]
Hi there, I have merged a [pull request](https://github.com/s-yadav/react-number-format/pull/200) for updating the README file for typescript usage.

One should use
```typescript
import { default as NumberFormat } from 'react-number-format';
```
instead of 
```typescript
import * as NumberFormat from 'react-number-format';
```

**Comment by HarlesPilter** [comment]
I have the same problem, using typescript 2.9.2. Using
`import { default as NumberFormat } from 'react-number-format';`
Didn't help. It still gives a warning on the component test that I use NumberFormat in. 
`Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.`

**Comment by s-yadav** [comment]
I guess this has been fixed. Also mention typescript usage (https://github.com/s-yadav/react-number-format#usage). That should work in most of case. If not you might want to look your tsconfig file.

**Comment by Meight** [comment]
Problem still arises from time to time (happens in some containers but not dummy components) even using

```javascript
import NumberFormat from 'react-number-format';
```

**Comment by sbaechler** [comment]
I still have the issue even with 3.6.2 and Typescript 3.1.4.

I think the problem is that NumberFormat does not export a CommonJS module by default.

Theoretically, this should work but it doesn't.
```
  "jest": {
    "transformIgnorePatterns": [
      "node_modules/(?!(react-number-format)/)"
    ]
  }
```
Setting `esModuleInterop` to `true` is not really an option since this breaks other parts of the app (e.g. Enzyme).

**Comment by sbaechler** [comment]
I found another (simpler) workaround for Jest that can be used until this issue is resolved. Just replace the module entirely.
Add this to package.json

```
  "jest": {
    "moduleNameMapper": {
      "react-number-format": "<rootDir>/test/__mocks__/number-format.js"
    }
  }
```

My mock file looks like this:
```
export default function () {
    return '';
}
```
