### ISSUE TITLE
TypeError: Unable to get property 'match' of undefined or null reference

### ISSUE THREAD

**Issue by lhtdesignde** [s-yadav/react-number-format#8]
I'm seeing ie11 errors with getCursorPosition. Seems like the match is trying to match on an inputvalue that is undefined or maybe not a string. My guess is that you could fix it by casting inputValue to a string. Here is the effected code:

```
	  getCursorPosition: function getCursorPosition(inputValue, formattedValue, cursorPos) {
	    var j = 0;
	    for (var i = 0; i < cursorPos; i++) {
	      if (!inputValue[i].match(/\d/) && inputValue[i] !== formattedValue[j]) continue;
	      while (inputValue[i] !== formattedValue[j] && j < formattedValue.length) {
	        j++;
	      }j++;
	    }
```

**Comment by s-yadav** [comment]
Ie 11 must be giving a number value when input type is tel. Will check that.

**Comment by s-yadav** [comment]
Can you check if this got fixed with latest release ?

**Comment by lhtdesignde** [comment]
Thanks for trying to fix this but unfortunately still getting the same error. For me it happens when a user sends the field empty. This happens when people decide to not start filling out the credit card number first. It seems to autofocus into the field right on load. then you click away and the error happens because it tries to validate on blur.

**Comment by s-yadav** [comment]
I am not doing any autofocus, or validating on blur. I checked this on IE, and I am not able to reproduce it . Can you try this http://codepen.io/s-yadav/pen/bpKNMa on your browser and let me know if this works.
Also share a codepen/jsfiddle or web link so I can debug.

**Comment by lhtdesignde** [comment]
Hey, sorry for the late reply! Thanks for making the codepen. With that I didn't get any errors. I updated to the latest of your releases but unfortunately I'm still seeing the issue. It's really hard to pinpoint it. I'm using redux-form 6 with it and it submits the field on blur and change to then run a validation. Maybe that could be a problem? I'm still unsure why it focuses it on load. That shouldn't happen but I don't have this with any other field, just where I use your library with and just in IE11.

**Comment by lhtdesignde** [comment]
Ok, now i only validate the field if it's not empty. Still it seems to trigger the match error when blurring it when it's empty. Can you maybe check when the `match` is running?

**Comment by s-yadav** [comment]
Can you send the snippet what you are using?
